# Generated by Django 3.1.1 on 2020-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
