# Generated by Django 3.1.1 on 2020-09-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortened_url',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
    ]
