# Generated by Django 3.1.1 on 2020-12-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('shortener', '0003_auto_20201004_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
    ]
