# Generated by Django 3.1.4 on 2020-12-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='device_id',
            field=models.CharField(default='deviceid', max_length=100),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='device_name',
            field=models.CharField(default='devicename', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='fcmkey',
            field=models.TextField(),
        ),
    ]
